version: 2.1
orbs:
  node: circleci/node@5
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@4.1.3
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      # Install dependency tools
      ## Checkout the code
      ## Install node v14.15
      ## Install AWS CLI
      ## Setup AWS CLI
      ## Setup Elastic Beanstalk CLI
      - checkout
      - node/install:
          node-version: '14.15'
      - aws-cli/install
      - aws-cli/setup
      - eb/setup

      # Install frontend dependencies via script in root package.json 
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install

      # Install backend API dependencies via script in root package.json 
      - run:
          name: Install API Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run api:install

      # Lint the frontend
      - run:
          name: Front-End Lint
          command: |
            npm run frontend:lint

      # Build the frontend app
      - run:
          name: Front-End Build
          command: |
            echo "building frontend"
            npm run frontend:build

      # Build the backend API      
      - run:
          name: API Build
          command: |
            echo "building API backend"
            npm run api:build

  # deploy stage
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      # Install dependency tools
      - checkout
      - node/install:
          node-version: '14.15'
      - aws-cli/install
      - aws-cli/setup
      - eb/setup
      
      # Check Working Directory
      - run:
          name: Check Working Directory
          command: |
            pwd
            ls -R

      # Deploy Frontend and Backend
      - run:
          name: Deploy Backend API and Frontend
          command: |
            echo "Deploying Backend API and Frontend"
            npm run deploy

# Workflows
workflows:
  udagram:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
